content_entity_example.contact.*:
  type: config_entity
  label: 'Contact config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
